Traderjoexyz and Rug Swap distinction
RuGenerous/rugenerous-frontend pull request #93
Opened 2021-12-04 22:13 UTC by GhostWalker562

## Summary
Switched out the links from the Trader Joes DEX to the Rug Swap DEX. In addition, since we have RLP to distinguish rug swap liquidity, it would only make sense that we should also distinguish the trader joes liquidity by making it JLP. Although, I'm not sure how the community would react, would they be knowledgable enough to understand LP vs JLP?

## TLDR
* Switched out trader joes link to rug swap
* Added a J to trader joe LP as we have two different liquidities contracts

2021-12-05 01:17 UTC, keeano92 commented
@camdengrieh @GhostWalker562 you mentioned how the community would react to these changes.  I looked over them and can approve them, I think it's a good chnage. Is this something we are entirely sure we want to deploy up?

2021-12-05 01:17 UTC, keeano92 commented
It's just staging too, so we can always adjust

2021-12-05 02:34 UTC, GhostWalker562 commented
Personally think it's fine a good change. I just don't want to spark confusion from RUG-AVAX JLP and RUG-AVAX LP. I know it's a minor change but idk there might be somebody who doesn't understand. But honestly I'm probably overthinking :P

2021-12-05 07:40 UTC, camdengrieh commented
rug-menu/index.tsx changes are not required, I have them in my latest commit for both exchanges, but happy to have the changes for the bond display name change

2021-12-05 07:42 UTC, camdengrieh requested changes, later dismissed
remove rug-menu/index.tsx changes as the changes have being applied in my latest commit

2021-12-05 07:44 UTC, GhostWalker562 commented
Done

2021-12-05 11:36 UTC, saschafuhrmann commented
In my opinion it' not a good idea to bring nearly all liquidity to Rug Dex. On all sites (CoinGecko, CoinMarketCap) there is TJ as market. How new interested people should know that they must go to RUG Dex? I personally look at CG/CMC for markets and not on the coin site. As a new guy when i see there is so low liquidity on TJ (a trusted site) I definitly won't invest in a coin that's name is RUG. And afaik on SnowDog the same decisions startet the downfall. I think a balanced LP on both swap is better

2021-12-06 04:47 UTC, keeano92 approved these changes

2021-12-06 04:47 UTC, merged